#!/usr/bin/env python3
"""
Generate publication-quality SRC momentum distribution schematic figure.

Recreates the conceptual three-panel figure showing:
  (a) NN interaction potential with SRC (correlated pair) wavefunction
  (b) Nuclear mean-field (Woods-Saxon) potential with single-particle wavefunction
  (c) Momentum distribution rho(k) decomposed into mean-field, tensor SRC, and
      central SRC components

Uses the academic-draw skill for matplotlib styling.
Attribution: Adapted from concepts in Hen et al., Rev. Mod. Phys. 89, 045002 (2017)

Author: Generated by Claude Code
"""

import os
import sys
from pathlib import Path

# ── academic-draw integration ──────────────────────────────────────────────
_DEFAULT_SKILL_SCRIPTS = r"D:\Something\research\MATE-Automation-V4\.claude\skills\academic-draw\scripts"
skill_scripts_env = os.environ.get("ACADEMIC_DRAW_SCRIPTS")
if skill_scripts_env:
    skill_scripts = Path(skill_scripts_env).resolve()
else:
    skill_scripts = Path(_DEFAULT_SKILL_SCRIPTS).resolve()

if not skill_scripts.exists():
    raise FileNotFoundError(
        f"academic-draw scripts not found at {skill_scripts}. "
        f"Set ACADEMIC_DRAW_SCRIPTS environment variable to the correct path."
    )

if str(skill_scripts) not in sys.path:
    sys.path.insert(0, str(skill_scripts))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
from matplotlib.patches import ConnectionPatch, FancyArrowPatch

from academic_style import (
    apply_academic_style,
    setup_academic_fonts,
    verify_academic_style,
)

apply_academic_style()
setup_academic_fonts()
verify_academic_style(hard_fail=True)

# ── Output paths ───────────────────────────────────────────────────────────
OUT_DIR = Path(
    r"D:\obsidian\OrbitOS\50_Resources\Physics\ExtractionDistillation"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_PDF = OUT_DIR / "SRC_momentum_distribution.pdf"
OUT_SVG = OUT_DIR / "SRC_momentum_distribution.svg"

# ── Color palette (Tol Bright, colorblind-friendly) ───────────────────────
C_INDIGO = "#332288"   # NN potential + WS potential curves
C_ORANGE = "#EE7733"   # Mean-field: wavefunction + connection + rho component
C_RED    = "#CC3311"   # Total rho(k) curve only
C_BLUE   = "#0077BB"   # Tensor SRC: wavefunction contribution + arrows + rho
C_TEAL   = "#009988"   # Central SRC: wavefunction contribution + arrows + rho
C_GREEN  = "#44AA44"   # Bold emphasis arrow in NN panel (green, matching original)
C_GRAY   = "#BBBBBB"   # k_F marker
C_BLACK  = "#000000"   # Axes, labels

# ── Log-scale floor ───────────────────────────────────────────────────────
LOG_FLOOR = 1e-10


# ══════════════════════════════════════════════════════════════════════════
#  Curve functions (Section 6)
# ══════════════════════════════════════════════════════════════════════════

def V_NN(r):
    """Schematic NN potential: repulsive core + attractive well (AV18-like)."""
    V_core = 600.0 * np.exp(-r / 0.25)
    V_well = -110.0 * np.exp(-((r - 1.0) ** 2) / (2 * 0.3 ** 2))
    V_tail = -5.0 * np.exp(-r / 1.4)
    return V_core + V_well + V_tail


def psi_SRC(r):
    """Relative wavefunction of SRC pair -- suppressed at short range."""
    suppression = 1.0 - np.exp(-(r / 0.8) ** 2)
    oscillation = np.sin(2.5 * r - 0.3) * np.exp(-0.3 * r)
    return suppression * oscillation


def V_WS(r, V0=50.0, R=3.5, a=0.65):
    """Standard Woods-Saxon potential."""
    return -V0 / (1.0 + np.exp((r - R) / a))


def psi_mf(r, b=1.8):
    """
    Mean-field 1p-shell wavefunction (n_r=0, l=1): ZERO radial nodes.
    Shape: r * exp(-r^2 / 2b^2) -- single smooth hump (nodeless).
    """
    x = r / b
    envelope = x * np.exp(-x ** 2 / 2.0)
    return envelope


def rho_meanfield(k, k_F=1.36):
    """Mean-field / IPM momentum distribution -- Gaussian-like, peaks below k_F."""
    sigma = 0.45
    return 1.5 * np.exp(-((k - 0.8) ** 2) / (2 * sigma ** 2))


def rho_src_tensor(k):
    """Tensor-correlated SRC pairs (np pairs, D-state) -- power-law tail."""
    amplitude = 0.08
    k0 = 1.5
    decay = 2.5
    raw = amplitude * (k / k0) ** 2 * np.exp(-decay * (k - k0)) * (k > k0).astype(float)
    return np.maximum(raw, LOG_FLOOR)


def rho_src_scalar(k):
    """Scalar/central SRC (pp/nn pairs) -- steeper power-law tail at higher k."""
    amplitude = 0.008
    k0 = 2.8
    decay = 2.0
    raw = amplitude * (k / k0) ** 3 * np.exp(-decay * (k - k0)) * (k > k0).astype(float)
    return np.maximum(raw, LOG_FLOOR)


def gaussian_smooth(y, sigma_pts=3):
    """Gaussian smoothing using numpy convolution (no scipy dependency)."""
    kernel_size = int(6 * sigma_pts) + 1
    x_kern = np.arange(kernel_size) - kernel_size // 2
    kernel = np.exp(-x_kern ** 2 / (2 * sigma_pts ** 2))
    kernel /= kernel.sum()
    return np.convolve(y, kernel, mode="same")


def curve_value_at(x_array, y_array, x_target):
    """Interpolate y at x_target from discrete curve data (nearest-neighbor)."""
    idx = np.argmin(np.abs(x_array - x_target))
    return y_array[idx]


# ══════════════════════════════════════════════════════════════════════════
#  Main figure construction
# ══════════════════════════════════════════════════════════════════════════

def create_morigin_figure():
    """Create and return the three-panel MORIGIN SRC schematic figure."""
    fig = plt.figure(figsize=(7.5, 4.8))

    # ── Create axes (Section 2.1) ──────────────────────────────────────
    ax_nn  = fig.add_axes([0.06, 0.56, 0.30, 0.38])
    ax_nuc = fig.add_axes([0.06, 0.08, 0.30, 0.38])
    ax_mom = fig.add_axes([0.50, 0.08, 0.46, 0.86])

    # ── Configure left panels: no spines, no ticks (Section 2.2) ──────
    for ax in [ax_nn, ax_nuc]:
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.tick_params(top=False, right=False, bottom=False, left=False)

    # ── Configure right panel (ax_mom) ─────────────────────────────────
    ax_mom.spines["top"].set_visible(False)
    ax_mom.spines["right"].set_visible(False)
    ax_mom.tick_params(top=False, right=False, which="both")

    # ── Set axis limits (Section 6.1) ──────────────────────────────────
    ax_nn.set_xlim(0, 5.0)
    ax_nn.set_ylim(-120, 300)
    ax_nuc.set_xlim(-8.0, 8.0)
    ax_nuc.set_ylim(-55, 20)
    ax_mom.set_xlim(0, 4.5)

    # ==================================================================
    # SECTION 5 -- Schematic axis lines (manual arrows at y=0)
    # ==================================================================

    # --- ax_nn axis lines ---
    # y=0 in data coords -> axes fraction: (0-(-120))/(300-(-120)) = 120/420
    y_zero_frac_nn = 120.0 / 420.0  # 0.2857

    # Vertical axis (energy)
    ax_nn.annotate(
        "", xy=(0, 1.05), xycoords="axes fraction",
        xytext=(0, -0.02), textcoords="axes fraction",
        arrowprops=dict(arrowstyle="->", color=C_BLACK, lw=1.0),
    )
    # Horizontal axis (r) -- passes through y=0 in data coords
    ax_nn.annotate(
        "", xy=(1.05, y_zero_frac_nn), xycoords="axes fraction",
        xytext=(-0.02, y_zero_frac_nn), textcoords="axes fraction",
        arrowprops=dict(arrowstyle="->", color=C_BLACK, lw=1.0),
    )
    # r [fm] label at arrow tip
    ax_nn.text(
        1.08, y_zero_frac_nn, r"$r$",
        transform=ax_nn.transAxes, fontsize=12, va="center", ha="left",
    )

    # --- ax_nuc axis lines ---
    # y=0 in data coords -> axes fraction: (0-(-55))/(20-(-55)) = 55/75
    y_zero_frac_nuc = 55.0 / 75.0  # 0.7333
    # x=0 in data coords -> axes fraction: (0-(-8))/(8-(-8)) = 8/16 = 0.5
    x_zero_frac_nuc = 0.5

    # Vertical axis at x=0 (center of symmetric well)
    ax_nuc.annotate(
        "", xy=(x_zero_frac_nuc, 1.05), xycoords="axes fraction",
        xytext=(x_zero_frac_nuc, -0.02), textcoords="axes fraction",
        arrowprops=dict(arrowstyle="->", color=C_BLACK, lw=1.0),
    )
    # Horizontal axis through y=0
    ax_nuc.annotate(
        "", xy=(1.05, y_zero_frac_nuc), xycoords="axes fraction",
        xytext=(-0.02, y_zero_frac_nuc), textcoords="axes fraction",
        arrowprops=dict(arrowstyle="->", color=C_BLACK, lw=1.0),
    )
    ax_nuc.text(
        1.08, y_zero_frac_nuc, r"$r$",
        transform=ax_nuc.transAxes, fontsize=12, va="center", ha="left",
    )

    # ==================================================================
    # SECTION 6 -- Mathematical curves
    # ==================================================================

    # --- 6.2 NN Potential ---
    r = np.linspace(0.01, 5.0, 500)
    v_nn = V_NN(r)
    v_nn_clipped = np.clip(v_nn, -120, 280)
    ax_nn.plot(r, v_nn_clipped, color=C_BLACK, linewidth=2.0, zorder=3)

    # --- 6.3 SRC wavefunction ---
    psi_src = psi_SRC(r)
    psi_src_scaled = psi_src / np.max(np.abs(psi_src)) * 50.0
    ax_nn.plot(r, psi_src_scaled, color=C_BLUE, linewidth=2.5, zorder=4)

    # --- 6.4 Woods-Saxon potential (symmetric well) ---
    r_nuc = np.linspace(-8.0, 8.0, 1000)
    v_ws = V_WS(np.abs(r_nuc))
    ax_nuc.plot(r_nuc, v_ws, color=C_BLACK, linewidth=2.0, zorder=3)

    # --- 6.5 Mean-field wavefunction (antisymmetric 1p state in full well) ---
    psi_mean = np.sign(r_nuc) * psi_mf(np.abs(r_nuc), b=1.8)
    psi_mean_scaled = psi_mean / np.max(np.abs(psi_mean)) * 15.0 - 25.0
    ax_nuc.plot(r_nuc, psi_mean_scaled, color=C_ORANGE, linewidth=2.5, zorder=4)

    # --- 6.6 Momentum distribution ---
    k = np.linspace(0.01, 4.5, 500)
    k_F = 1.36

    rho_mf = rho_meanfield(k, k_F=k_F)
    rho_tensor = rho_src_tensor(k)
    rho_scalar = rho_src_scalar(k)
    rho_total = rho_mf + rho_tensor + rho_scalar
    rho_total_smooth = gaussian_smooth(rho_total, sigma_pts=3)

    ax_mom.set_yscale("log")

    # Individual components FIRST (zorder=5, above total)
    ax_mom.plot(
        k, rho_mf, color=C_ORANGE, linewidth=2.0, linestyle="--",
        zorder=5, label=r"Mean-field (IPM)",
    )
    ax_mom.plot(
        k, rho_tensor, color=C_BLUE, linewidth=2.0, linestyle=":",
        zorder=5, label=r"Tensor SRC ($np$)",
    )
    ax_mom.plot(
        k, rho_scalar, color=C_GREEN, linewidth=2.0, linestyle="-.",
        zorder=5, label=r"Central SRC ($pp/nn$)",
    )
    # Total curve BELOW components (zorder=4)
    ax_mom.plot(
        k, rho_total_smooth, color=C_RED, linewidth=2.5, linestyle="-",
        zorder=4, label=r"$\rho(k)$ total",
    )

    ax_mom.set_ylim(1e-4, 2.0)

    # Y-axis log ticks (configured AFTER set_yscale)
    ax_mom.yaxis.set_major_locator(ticker.LogLocator(base=10, numticks=10))
    ax_mom.yaxis.set_major_formatter(ticker.LogFormatterSciNotation())
    ax_mom.tick_params(axis="y", direction="in", length=5, width=1.0, which="both")

    # X-axis ticks
    ax_mom.set_xticks([1, 2, 3, 4])
    ax_mom.set_xticklabels(["1", "2", "3", "4"])
    ax_mom.tick_params(axis="x", direction="in", length=5, width=1.0)

    # ==================================================================
    # SECTION 7 -- Labels and annotations
    # ==================================================================

    # --- 7.1 Panel labels ---
    # Removed formal (a)(b)(c) labels to match original figure style.
    # Descriptive text labels ("NN interaction", "nuclear potential") serve
    # as panel identifiers instead (see 7.2 below).

    # --- 7.2 Physics labels ---
    # PHYSICS AUDIT FIX: "NN interaction" not "n-n interaction"
    ax_nn.text(
        0.95, 0.95, "NN interaction", transform=ax_nn.transAxes,
        fontsize=11, fontstyle="italic", va="top", ha="right", color=C_BLACK,
    )
    ax_nuc.text(
        0.50, -0.08, "nuclear potential", transform=ax_nuc.transAxes,
        fontsize=11, fontstyle="italic", va="bottom", ha="center", color=C_BLACK,
    )

    # V(r) labels on y-axes (outside axes bounds)
    ax_nn.text(
        -0.06, 0.92, r"$V(r)$", transform=ax_nn.transAxes,
        fontsize=12, va="center", ha="right", clip_on=False,
    )
    ax_nuc.text(
        x_zero_frac_nuc - 0.04, 0.92, r"$V(r)$", transform=ax_nuc.transAxes,
        fontsize=12, va="center", ha="right", clip_on=False,
    )

    # --- 7.2b Curve name annotations ---
    # NN panel: potential and SRC wavefunction
    ax_nn.text(
        2.5, -80, r"$V_{NN}(r)$",
        fontsize=10, color=C_BLACK, va="center", ha="center",
    )
    ax_nn.text(
        3.5, 60, r"$\psi_\mathrm{SRC}(r)$",
        fontsize=10, color=C_BLUE, va="center", ha="center",
    )
    # Nuclear panel: Woods-Saxon potential and mean-field wavefunction
    ax_nuc.text(
        -6.0, -18, r"$V_\mathrm{WS}(r)$",
        fontsize=10, color=C_BLACK, va="center", ha="center",
    )
    ax_nuc.text(
        4.5, -10, r"$\psi_{1p}(r)$",
        fontsize=10, color=C_ORANGE, va="center", ha="center",
    )

    # --- 7.3 Momentum panel labels ---
    ax_mom.set_ylabel(r"$\rho(k)$  (log)", fontsize=12, labelpad=5)
    ax_mom.set_xlabel(r"Momentum  [fm$^{-1}$]", fontsize=12, labelpad=5)

    # --- 7.4 k_F marker ---
    ax_mom.axvline(x=k_F, color=C_GRAY, linewidth=1.2, linestyle="--", zorder=2)
    ax_mom.annotate(
        r"$k_F$", xy=(k_F, 1.5), xytext=(k_F + 0.08, 1.5),
        fontsize=11, color="#666666", va="center", ha="left",
    )

    # --- 7.5 SRC region annotation ---
    # Place at very bottom of plot in clear space
    ax_mom.annotate(
        "", xy=(2.0, 1.5e-4), xytext=(4.3, 1.5e-4),
        arrowprops=dict(arrowstyle="<->", color=C_GREEN, lw=1.2),
    )
    ax_mom.text(
        3.15, 2e-4, "SRC dominant", fontsize=9, ha="center", va="bottom",
        color=C_GREEN, fontstyle="italic",
    )

    # --- 7.6 Legend ---
    ax_mom.legend(
        loc="upper right", fontsize=7.5, frameon=False,
        labelspacing=0.3, handlelength=1.8, borderaxespad=0.3,
        bbox_to_anchor=(1.0, 0.98),
    )

    # ==================================================================
    # SECTION 8 -- Arrows and connectors
    # ==================================================================

    # --- 8.1 Cross-axes connection arrows ---
    # Dashed, subtle arrows that don't compete with data curves

    # Arrow 1: Mean-field wavefunction (ax_nuc) -> low-k region of rho_mf (ax_mom)
    mf_src_x = 5.5
    mf_src_y = curve_value_at(r_nuc, psi_mean_scaled, mf_src_x)
    mf_tgt_x = 0.4
    mf_tgt_y = curve_value_at(k, rho_mf, mf_tgt_x)

    arrow_mf = ConnectionPatch(
        xyA=(mf_src_x, mf_src_y), coordsA="data", axesA=ax_nuc,
        xyB=(mf_tgt_x, mf_tgt_y), coordsB="data", axesB=ax_mom,
        arrowstyle="-|>", color=C_ORANGE, linewidth=1.0, alpha=0.45,
        connectionstyle="arc3,rad=0.25", linestyle="--",
        mutation_scale=10, zorder=1,
    )
    fig.add_artist(arrow_mf)

    # Arrow 2: SRC wavefunction (ax_nn) -> tensor SRC high-k (ax_mom)
    src_blue_src_x = 4.2
    src_blue_src_y = curve_value_at(r, psi_src_scaled, src_blue_src_x)
    src_blue_tgt_x = 1.8
    src_blue_tgt_y = curve_value_at(k, rho_tensor, src_blue_tgt_x)

    arrow_src_blue = ConnectionPatch(
        xyA=(src_blue_src_x, src_blue_src_y), coordsA="data", axesA=ax_nn,
        xyB=(src_blue_tgt_x, src_blue_tgt_y), coordsB="data", axesB=ax_mom,
        arrowstyle="-|>", color=C_BLUE, linewidth=1.0, alpha=0.45,
        connectionstyle="arc3,rad=-0.3", linestyle="--",
        mutation_scale=10, zorder=1,
    )
    fig.add_artist(arrow_src_blue)

    # Arrow 3: SRC wavefunction (ax_nn) -> central SRC teal region (ax_mom)
    src_teal_src_x = 3.5
    src_teal_src_y = curve_value_at(r, psi_src_scaled, src_teal_src_x)
    src_teal_tgt_x = 2.5
    src_teal_tgt_y = curve_value_at(k, rho_scalar, src_teal_tgt_x)

    arrow_src_teal = ConnectionPatch(
        xyA=(src_teal_src_x, src_teal_src_y), coordsA="data", axesA=ax_nn,
        xyB=(src_teal_tgt_x, src_teal_tgt_y), coordsB="data", axesB=ax_mom,
        arrowstyle="-|>", color=C_GREEN, linewidth=1.0, alpha=0.45,
        connectionstyle="arc3,rad=-0.2", linestyle="--",
        mutation_scale=10, zorder=1,
    )
    fig.add_artist(arrow_src_teal)

    # --- 8.2 Conceptual emphasis arrows ---

    # Two BIG, BOLD arrows in ax_nn: correlated nucleon pair pointing at
    # repulsive core -- matching the original's prominent green & blue arrows
    arrow_pair_1 = FancyArrowPatch(
        posA=(0.7, 250), posB=(0.7, 60),
        arrowstyle="->,head_length=14,head_width=10",
        color=C_GREEN, linewidth=5.0, alpha=0.85, zorder=10,
    )
    ax_nn.add_patch(arrow_pair_1)

    arrow_pair_2 = FancyArrowPatch(
        posA=(1.3, 220), posB=(1.3, 20),
        arrowstyle="->,head_length=14,head_width=10",
        color=C_BLUE, linewidth=5.0, alpha=0.85, zorder=10,
    )
    ax_nn.add_patch(arrow_pair_2)

    # ==================================================================
    # Attribution text (bottom of figure, small font)
    # ==================================================================
    # Rev04 fix H5: move attribution lower to avoid collision with x-axis label
    fig.text(
        0.5, -0.03,
        "Adapted from concepts in Hen et al., Rev. Mod. Phys. 89, 045002 (2017)",
        ha="center", va="top", fontsize=7, fontstyle="italic", color="#666666",
    )

    return fig


# ══════════════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("Generating SRC momentum distribution schematic...")
    fig = create_morigin_figure()

    # Save PDF (vector, for publication) -- NO tight_layout()!
    fig.savefig(str(OUT_PDF), bbox_inches="tight", dpi=300)
    print(f"  PDF saved: {OUT_PDF}")

    # Save SVG (vector) -- same figure, no need to recreate
    fig.savefig(str(OUT_SVG), bbox_inches="tight", dpi=300)
    print(f"  SVG saved: {OUT_SVG}")

    plt.close(fig)
    print("Done.")
